from django.urls import path
from .views import base as views
from .views.api import api

app_name = "orgapy"

urlpatterns = [
    path("", views.view_landing, name="landing"),
    path("about", views.view_about, name="about"),
    path("home", views.view_home, name="home"),
    path("docs", views.view_documents, name="documents"),
    path("docs/create", views.view_create_document, name="create_document"),
    path("docs/save", views.view_save_document, name="save_document"),
    path("docs/<nonce>", views.view_document, name="document"),
    path("docs/<nonce>/edit", views.view_edit_document, name="edit_document"),
    path("docs/<nonce>/hidden", views.view_toggle_document_hidden, name="toggle_document_hidden"),
    path("docs/<nonce>/pin", views.view_toggle_document_pin, name="toggle_document_pin"),
    path("docs/<nonce>/public", views.view_toggle_document_public, name="toggle_document_public"),
    path("docs/<nonce>/delete", views.view_delete_document, name="delete_document"),
    path("docs/<nonce>/restore", views.view_restore_document, name="restore_document"),
    path("docs/<nonce>/destroy", views.view_destroy_document, name="destroy_document"),
    path("notes", views.view_notes, name="notes"),
    path("sheets", views.view_sheets, name="sheets"),
    path("maps", views.view_maps, name="maps"),
    path("projects", views.view_projects, name="projects"),
    path("projects/<nonce>", views.view_project, name="project"),
    path("projects/<nonce>/delete", views.view_delete_project, name="delete_project"),
    path("categories/", views.view_categories, name="categories"),
    path("categories/<name>", views.view_category, name="category"),
    path("categories/<name>/edit", views.view_edit_category, name="edit_category"),
    path("categories/<name>/delete", views.view_delete_category, name="delete_category"),
    path("progress", views.view_progress, name="progress"),
    path("progress/log/create", views.view_create_progress_log, name="create_progress_log"),
    path("progress/log/save", views.view_save_progress_log, name="save_progress_log"),
    path("progress/log/<object_id>", views.view_edit_progress_log, name="edit_progress_log"),
    path("progress/log/<object_id>/delete", views.view_delete_progress_log, name="delete_progress_log"),
    path("settings", views.view_settings, name="settings"),
    path("settings/calendar", views.view_calendar_form, name="calendar_form"),
    path("mood", views.view_mood, name="mood"),
    path("mood/<object_id>/delete", views.view_delete_mood_log, name="delete_mood_log"),
    path("trash", views.view_trash, name="trash"),
    path("trash/restore", views.view_restore_all_documents, name="restore_all"),
    path("trash/destroy", views.view_destroy_all_documents, name="destroy_all"),
    path("groceries", views.view_groceries, name="groceries"),
    path("tasks", views.view_tasks, name="tasks"),
    path("objectives", views.view_objectives, name="objectives"),
    path("suggestions", views.view_suggestions, name="suggestions"),
    path("api", api, name="api"),
]
