from django.urls import path
from . import views

app_name = "orgapy"

urlpatterns = [
    path("about", views.about, name="about"),
    path("create-note", views.create_note, name="create_note"),
    path("save-note", views.save_note, name="save_note"),
    path("note/<nid>", views.view_note, name="view_note"),
    path("note/<nid>/edit", views.edit_note, name="edit_note"),
    path("note/<nid>/export", views.export_note, name="export_note"),
    path("note/<nid>/delete", views.delete_note, name="delete_note"),
    path("note/<nid>/pin", views.toggle_pin, name="toggle_pin"),
    path("note/<nid>/public", views.toggle_public, name="toggle_public"),
    path("sheets", views.view_sheets, name="sheets"),
    path("sheet/create", views.create_sheet, name="create_sheet"),
    path("sheet/save", views.save_sheet, name="save_sheet"),
    path("sheet/<sid>", views.view_sheet, name="view_sheet"),
    path("sheet/<sid>/raw", views.view_sheet_raw, name="view_sheet_raw"),
    path("sheet/<sid>/edit", views.edit_sheet, name="edit_sheet"),
    path("sheet/<sid>/delete", views.delete_sheet, name="delete_sheet"),
    path("sheet/<sid>/public", views.toggle_public_sheet, name="toggle_public_sheet"),
    path("sheet-group/create", views.create_sheet_group, name="create_sheet_group"),
    path("sheet-group/save", views.save_sheet_group, name="save_sheet_group"),
    path("sheet-group/<sid>", views.view_sheet_group, name="view_sheet_group"),
    path("sheet-group/<sid>/edit", views.edit_sheet_group, name="edit_sheet_group"),
    path("sheet-group/<sid>/delete", views.delete_sheet_group, name="delete_sheet_group"),
    path("", views.view_projects, name="projects_2"),
    path("notes", views.view_notes, name="notes"),
    path("public/<nid>", views.view_public_note, name="view_public_note"),
    path("quotes", views.view_quotes, name="quotes"),
    path("quotes/<author>", views.view_quotes, name="quotes_author"),
    path("quotes/<author>/<work>", views.view_quotes, name="quotes_work"),
    path("create-quote", views.create_quote, name="create_quote"),
    path("categories", views.view_categories, name="categories"),
    path("categories/<cid>/edit", views.edit_category, name="edit_category"),
    path("categories/<cid>/delete", views.delete_category, name="delete_category"),
    path("api/suggestions", views.api_suggestions, name="api_suggestions"),
    path("projects", views.view_projects, name="projects"),
    path("api/project/list", views.api_project_list, name="api_project_list"),
    path("api/project/edit", views.api_project_edit, name="api_project_edit"),
    path("api/project/delete", views.api_project_delete, name="api_project_delete"),
    path("api/project/create", views.api_project_create, name="api_project_create"),
    path("api/project/ranks", views.api_project_edit_ranks, name="api_project_edit_ranks"),
    path("api/objective/list", views.api_objective_list, name="api_objective_list"),
    path("api/objective/history", views.api_objective_history, name="api_objective_history"),
    path("api/calendar/list", views.api_calendar_list, name="api_calendar_list"),
    path("api/calendar/delete", views.api_calendar_delete, name="api_calendar_delete"),
    path("api/calendar/complete", views.api_calendar_complete, name="api_calendar_complete"),
    path("api/calendar/add", views.api_calendar_add, name="api_calendar_add"),
    path("api/calendar/add-task", views.api_calendar_add_task, name="api_calendar_add_task"),
    path("api/note-title", views.api_note_title, name="api_note_title"),
    path("api/sheet/data", views.api_sheet_data, name="api_sheet_data"),
    path("api/sheet/save", views.api_sheet_save, name="api_sheet_save"),
]
