# Generated by Django 2.2.9 on 2020-01-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'order_with_respect_to': 'name',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('public', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, to='orgapy.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orgapy.Note')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('abstract', models.TextField(default='')),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orgapy.Note')),
                ('date_due', models.DateField(blank=True, null=True)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
