# Generated by Django 2.2.9 on 2020-01-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_access',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
