# Generated by Django 5.2.8 on 2025-12-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgapy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("AC", "Active"), ("IN", "Inactive"), ("AR", "Archived")],
                default="AC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
