# Generated by Django 2.2.9 on 2020-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0002_note_date_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_access',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_modification',
            field=models.DateTimeField(),
        ),
    ]
