# Generated by Django 5.2.8 on 2026-01-01 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgapy", "0002_project_status_alter_project_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="mood_activities",
            field=models.TextField(default="Hiking 🥾\nRunning 🏃\nParty 🎉"),
        ),
        migrations.AddField(
            model_name="settings",
            name="mood_log_hours",
            field=models.PositiveIntegerField(
                default=19,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
        migrations.CreateModel(
            name="MoodLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("mood", models.PositiveIntegerField()),
                ("energy", models.PositiveIntegerField()),
                ("health", models.PositiveIntegerField()),
                ("stress", models.PositiveIntegerField()),
                ("activities", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "created_at"],
            },
        ),
    ]
