# Generated by Django 2.2.9 on 2020-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0003_auto_20200120_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_access',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_modification',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
