# Generated by Django 5.2.8 on 2026-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgapy", "0003_settings_mood_activities_settings_mood_log_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("AC", "Active"),
                    ("IN", "Inactive"),
                    ("AR", "Archived"),
                    ("FU", "Future"),
                ],
                default="AC",
                max_length=2,
            ),
        ),
    ]
