# Generated by Django 2.2.9 on 2020-01-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0004_auto_20200120_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalDavSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=5232)),
                ('protocol', models.CharField(default='https', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
