# Generated by Django 5.2.6 on 2026-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='groceries_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
