# Generated by Django 5.2.8 on 2026-02-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgapy", "0005_settings_groceries_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="mood_log_lookback_days",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
