# Generated by Django 5.2.6 on 2026-04-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0006_settings_mood_log_lookback_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
