# Generated by Django 3.1.4 on 2021-01-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0008_auto_20210111_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
    ]
