# Generated by Django 3.1.4 on 2021-01-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0009_remove_note_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalDavSettings',
        ),
    ]
