# Generated by Django 3.2.1 on 2021-05-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0010_delete_caldavsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='step',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='DailyObjective',
        ),
        migrations.DeleteModel(
            name='WeeklyObjective',
        ),
    ]
