# Generated by Django 5.2.6 on 2026-04-17 13:36

import orgapy.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0010_documents_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='map_refs',
        ),
        migrations.RemoveField(
            model_name='note',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_refs',
        ),
        migrations.RemoveField(
            model_name='note',
            name='sheet_refs',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='note',
        ),
        #migrations.RemoveField(
        #    model_name='progresscounter',
        #    name='user',
        #),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sheetgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='limit_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress_current',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress_max',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress_min',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rank',
        ),
        migrations.AlterField(
            model_name='document',
            name='nonce',
            field=models.CharField(blank=True, default=orgapy.utils.generate_nonce, max_length=12, unique=True),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='ProgressCounter',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Sheet',
        ),
        migrations.DeleteModel(
            name='SheetGroup',
        ),
    ]
