# Generated by Django 5.2.6 on 2026-04-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0013_nonces_references'),
    ]

    operations = []
