# Generated by Django 5.2.6 on 2026-04-18 07:56

import orgapy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0015_generate_project_nonces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nonce',
            field=models.CharField(blank=True, default=orgapy.models.generate_project_nonce, max_length=12, unique=True),
        ),
    ]
