# Generated by Django 4.1.7 on 2023-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0015_remove_objective_step_objective_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
