# Generated by Django 5.2.6 on 2026-04-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0015_generate_project_nonces'),
    ]

    operations = []
