# Generated by Django 6.0.2 on 2026-04-21 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgapy", "0017_enable_document_full_text_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
