# Generated by Django 5.2.6 on 2026-04-22 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0018_document_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='nonce',
        ),
        migrations.AddField(
            model_name='project',
            name='date_archived',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
