# Generated by Django 5.2.6 on 2026-04-29 07:10

import orgapy.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0020_fix_document_fts_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='categories',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='document',
            name='nonce',
            field=models.CharField(blank=True, default=orgapy.models.generate_document_nonce, max_length=12, unique=True),
        ),
    ]
