# Generated by Django 4.1.7 on 2023-09-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0020_alter_quote_options_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgapy.note'),
        ),
    ]
