# Generated by Django 4.2.5 on 2023-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0021_project_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='period',
        ),
        migrations.AddField(
            model_name='objective',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
