# Generated by Django 4.2.5 on 2023-10-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0022_remove_objective_date_start_remove_objective_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgapy.note'),
        ),
    ]
