# Generated by Django 4.1.7 on 2023-10-16 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgapy', '0023_alter_project_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='type',
            field=models.CharField(choices=[('CD', 'Calendar'), ('TK', 'Tasks')], default='CD', max_length=2),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
