# Generated by Django 4.1.7 on 2023-10-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0024_calendar_type_alter_calendar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='type',
        ),
        migrations.AddField(
            model_name='calendar',
            name='tasks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
