# Generated by Django 4.1.7 on 2023-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0026_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='styles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
