# Generated by Django 4.1.7 on 2023-10-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0027_sheet_styles_alter_sheet_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='styles',
            new_name='config',
        ),
    ]
