# Generated by Django 4.1.7 on 2023-11-19 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgapy', '0027_objective_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('recurring_mode', models.CharField(choices=[('ON', 'Once'), ('DY', 'Daily'), ('WK', 'Weekly'), ('MN', 'Monthly'), ('YR', 'Yearly')], default='ON', max_length=2)),
                ('recurring_period', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('recurring_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgapy.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
