# Generated by Django 4.1.7 on 2023-11-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0028_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='tasks',
        ),
    ]
