# Generated by Django 5.0.7 on 2024-10-10 08:39

import orgapy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0034_auto_20241010_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='nonce',
            field=models.TextField(blank=True, default=orgapy.models.generate_nonce, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='nonce',
            field=models.TextField(blank=True, default=orgapy.models.generate_nonce, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='nonce',
            field=models.TextField(blank=True, default=orgapy.models.generate_nonce, max_length=12, unique=True),
        ),
    ]
