# Generated by Django 5.1.6 on 2025-02-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0035_auto_20241010_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
