# Generated by Django 5.1.6 on 2025-02-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0037_populate_quote_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='from_work',
        ),
    ]
