# Generated by Django 5.1.6 on 2025-02-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0038_remove_quote_from_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='title',
        ),
    ]
