# Generated by Django 5.1.6 on 2025-02-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0039_remove_quote_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='author',
        ),
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
