# Generated by Django 5.1.6 on 2025-02-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0043_populate_objective_attrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='rules',
        ),
    ]
