# Generated by Django 5.1.7 on 2025-04-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0045_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='lookahead',
        ),
        migrations.AddField(
            model_name='settings',
            name='calendar_lookahead',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
