# Generated by Django 5.1.7 on 2025-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0046_remove_calendar_lookahead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
