# Generated by Django 5.0.7 on 2025-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0048_note_map_refs_note_note_refs_note_sheet_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='beach_mode',
            field=models.BooleanField(default=False),
        ),
    ]
