# Generated by Django 5.0.7 on 2025-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0049_settings_beach_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='categories',
            field=models.ManyToManyField(blank=True, to='orgapy.category'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='categories',
            field=models.ManyToManyField(blank=True, to='orgapy.category'),
        ),
    ]
