# Generated by Django 5.0.7 on 2025-08-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0050_map_categories_sheet_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='map',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
