# Generated by Django 5.1.7 on 2025-08-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0052_alter_calendar_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['-date_modification']},
        ),
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ['-date_modification']},
        ),
    ]
