# Generated by Django 5.1.7 on 2025-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0053_alter_map_options_alter_sheet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='date_deletion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='date_deletion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='date_deletion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
