# Generated by Django 5.1.7 on 2025-09-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0054_map_date_deletion_map_deleted_note_date_deletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='trash_period',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
