# Generated by Django 5.1.7 on 2025-09-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0056_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
