# Generated by Django 5.2.6 on 2025-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapy', '0058_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive'), ('AR', 'Archived')], default='AC', max_length=2),
        ),
    ]
